import type { Template } from '@/lib/types'

export const SEED_TEMPLATES: Omit<Template, 'id' | 'created_at'>[] = [
  {
    name: 'Modern Bento',
    slug: 'modern-bento',
    description: 'Clean bento-grid layout with bold typography. Perfect for tech and web projects.',
    category: 'web-dev',
    thumbnail_url: null,
    is_premium: false,
    sort_order: 1,
    structure: [
      { type: 'cover', title: '', subtitle: '', client_name: '', date: '' },
      { type: 'about', heading: 'About Us', body: '' },
      { type: 'scope', heading: 'Project Scope', items: [] },
      { type: 'deliverables', heading: 'Deliverables', items: [] },
      { type: 'timeline', heading: 'Timeline', milestones: [] },
      { type: 'pricing', heading: 'Investment', line_items: [], total: 0 },
      { type: 'terms', heading: 'Terms & Conditions', body: '' },
      { type: 'next_steps', heading: 'Next Steps', body: '', cta_text: 'Accept & Pay' },
    ],
  },
  {
    name: 'Minimalist Pro',
    slug: 'minimalist-pro',
    description: 'Elegant whitespace-driven design. Ideal for consulting and strategy.',
    category: 'consulting',
    thumbnail_url: null,
    is_premium: false,
    sort_order: 2,
    structure: [
      { type: 'cover', title: '', subtitle: '', client_name: '', date: '' },
      { type: 'about', heading: 'Who We Are', body: '' },
      { type: 'scope', heading: 'Engagement Scope', items: [] },
      { type: 'timeline', heading: 'Project Phases', milestones: [] },
      { type: 'pricing', heading: 'Fee Structure', line_items: [], total: 0 },
      { type: 'terms', heading: 'Agreement Terms', body: '' },
      { type: 'next_steps', heading: "Let's Begin", body: '', cta_text: 'Approve Proposal' },
    ],
  },
  {
    name: 'Bold Creative',
    slug: 'bold-creative',
    description: 'Vibrant gradients and dynamic layout. Great for design and branding work.',
    category: 'design',
    thumbnail_url: null,
    is_premium: false,
    sort_order: 3,
    structure: [
      { type: 'cover', title: '', subtitle: '', client_name: '', date: '' },
      { type: 'about', heading: 'Our Creative Vision', body: '' },
      { type: 'scope', heading: 'Creative Scope', items: [] },
      { type: 'deliverables', heading: 'What You Get', items: [] },
      { type: 'timeline', heading: 'Creative Timeline', milestones: [] },
      { type: 'pricing', heading: 'Investment', line_items: [], total: 0 },
      { type: 'terms', heading: 'Working Together', body: '' },
      { type: 'next_steps', heading: "Let's Create", body: '', cta_text: 'Start Project' },
    ],
  },
  {
    name: 'Growth Marketing',
    slug: 'growth-marketing',
    description: 'Data-driven layout with metrics focus. Built for marketing proposals.',
    category: 'marketing',
    thumbnail_url: null,
    is_premium: false,
    sort_order: 4,
    structure: [
      { type: 'cover', title: '', subtitle: '', client_name: '', date: '' },
      { type: 'about', heading: 'About Our Agency', body: '' },
      { type: 'scope', heading: 'Marketing Strategy', items: [] },
      { type: 'deliverables', heading: 'Deliverables & KPIs', items: [] },
      { type: 'timeline', heading: 'Campaign Timeline', milestones: [] },
      { type: 'pricing', heading: 'Monthly Investment', line_items: [], total: 0 },
      { type: 'terms', heading: 'Terms of Service', body: '' },
      { type: 'next_steps', heading: 'Launch Plan', body: '', cta_text: 'Approve & Launch' },
    ],
  },
  {
    name: 'Studio Lens',
    slug: 'studio-lens',
    description: 'Visual-first layout designed for photographers and videographers.',
    category: 'photography',
    thumbnail_url: null,
    is_premium: false,
    sort_order: 5,
    structure: [
      { type: 'cover', title: '', subtitle: '', client_name: '', date: '' },
      { type: 'about', heading: 'About the Photographer', body: '' },
      { type: 'scope', heading: 'Session Details', items: [] },
      { type: 'deliverables', heading: 'What You Receive', items: [] },
      { type: 'pricing', heading: 'Package & Pricing', line_items: [], total: 0 },
      { type: 'terms', heading: 'Booking Terms', body: '' },
      { type: 'next_steps', heading: 'Book Your Session', body: '', cta_text: 'Book & Pay' },
    ],
  },
  {
    name: 'Premium Agency',
    slug: 'premium-agency',
    description: 'High-end executive layout with rich sections. For premium client projects.',
    category: 'general',
    thumbnail_url: null,
    is_premium: true,
    sort_order: 6,
    structure: [
      { type: 'cover', title: '', subtitle: '', client_name: '', date: '' },
      { type: 'about', heading: 'About Our Agency', body: '' },
      { type: 'scope', heading: 'Project Scope', items: [] },
      { type: 'deliverables', heading: 'Deliverables', items: [] },
      { type: 'timeline', heading: 'Milestones', milestones: [] },
      { type: 'pricing', heading: 'Investment Summary', line_items: [], total: 0 },
      { type: 'terms', heading: 'Terms & Conditions', body: '' },
      { type: 'next_steps', heading: 'Next Steps', body: '', cta_text: 'Accept Proposal' },
    ],
  },
  {
    name: 'Neon Startup',
    slug: 'neon-startup',
    description: 'Dark theme with neon accents. Perfect for tech startups and SaaS.',
    category: 'web-dev',
    thumbnail_url: null,
    is_premium: true,
    sort_order: 7,
    structure: [
      { type: 'cover', title: '', subtitle: '', client_name: '', date: '' },
      { type: 'about', heading: 'Why Us', body: '' },
      { type: 'scope', heading: 'Technical Scope', items: [] },
      { type: 'deliverables', heading: 'Deliverables', items: [] },
      { type: 'timeline', heading: 'Sprint Plan', milestones: [] },
      { type: 'pricing', heading: 'Budget Breakdown', line_items: [], total: 0 },
      { type: 'terms', heading: 'Agreement', body: '' },
      { type: 'next_steps', heading: 'Ship It', body: '', cta_text: 'Let\'s Build' },
    ],
  },
  {
    name: 'Video Production',
    slug: 'video-production',
    description: 'Cinematic layout for video and motion projects.',
    category: 'video',
    thumbnail_url: null,
    is_premium: true,
    sort_order: 8,
    structure: [
      { type: 'cover', title: '', subtitle: '', client_name: '', date: '' },
      { type: 'about', heading: 'About the Director', body: '' },
      { type: 'scope', heading: 'Production Scope', items: [] },
      { type: 'deliverables', heading: 'Final Deliverables', items: [] },
      { type: 'timeline', heading: 'Production Schedule', milestones: [] },
      { type: 'pricing', heading: 'Production Budget', line_items: [], total: 0 },
      { type: 'terms', heading: 'Production Agreement', body: '' },
      { type: 'next_steps', heading: 'Action!', body: '', cta_text: 'Green Light' },
    ],
  },
  {
    name: 'SEO Blueprint',
    slug: 'seo-blueprint',
    description: 'Technical SEO proposal with audit-style sections.',
    category: 'marketing',
    thumbnail_url: null,
    is_premium: true,
    sort_order: 9,
    structure: [
      { type: 'cover', title: '', subtitle: '', client_name: '', date: '' },
      { type: 'about', heading: 'Our SEO Expertise', body: '' },
      { type: 'scope', heading: 'SEO Strategy', items: [] },
      { type: 'deliverables', heading: 'Monthly Deliverables', items: [] },
      { type: 'timeline', heading: 'SEO Roadmap', milestones: [] },
      { type: 'pricing', heading: 'Monthly Retainer', line_items: [], total: 0 },
      { type: 'terms', heading: 'Service Agreement', body: '' },
      { type: 'next_steps', heading: 'Start Ranking', body: '', cta_text: 'Start SEO' },
    ],
  },
  {
    name: 'Mobile App Builder',
    slug: 'mobile-app',
    description: 'Structured layout for mobile app development proposals.',
    category: 'web-dev',
    thumbnail_url: null,
    is_premium: true,
    sort_order: 10,
    structure: [
      { type: 'cover', title: '', subtitle: '', client_name: '', date: '' },
      { type: 'about', heading: 'Our Development Team', body: '' },
      { type: 'scope', heading: 'App Scope & Features', items: [] },
      { type: 'deliverables', heading: 'Deliverables', items: [] },
      { type: 'timeline', heading: 'Development Sprints', milestones: [] },
      { type: 'pricing', heading: 'Development Cost', line_items: [], total: 0 },
      { type: 'terms', heading: 'Development Agreement', body: '' },
      { type: 'next_steps', heading: 'Launch Your App', body: '', cta_text: 'Start Development' },
    ],
  },
]
